version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: tutor-me-good-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: tutor-me-good
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis/redis-stack-server:latest
    container_name: tutor-me-good-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
