import type { Activity } from "./activities.types";

export const getActivities = () => {
  return activities;
};

const activities: Activity[] = [
  {
    id: "algebra-basics-7a",
    type: "assignment",
    title: "Assignment Completed",
    description: "Assignment 'Algebra Basics' completed by Group 7A",
    timestamp: "2025-06-29T14:30:00Z",
    status: "completed",
    details: {
      assignmentName: "Algebra Basics",
      groupName: "Group 7A",
      completionRate: 95,
      averageScore: 87,
      timeSpent: 45,
      studentsCompleted: 12,
      totalStudents: 13,
      topPerformers: ["Anna Müller", "Lisa Weber", "Emma Bauer"],
      strugglingStudents: ["Tom Fischer"],
      submissionTime: "2025-06-29T14:30:00Z",
      feedback:
        "Excellent work overall. Focus on algebraic manipulation for struggling students.",
    },
    relatedEntities: {
      groups: ["7A"],
      assignments: ["algebra-basics"],
      students: ["anna-muller", "lisa-weber", "emma-bauer", "tom-fischer"],
    },
  },
  {
    id: "max-muller-8b",
    type: "student",
    title: "New Student Added",
    description: "New student 'Max Müller' added to Group 8B",
    timestamp: "2025-06-28T10:15:00Z",
    status: "info",
    details: {
      studentName: "Max Müller",
      email: "max.mueller@school.de",
      groupName: "Group 8B",
      grade: "10A",
      enrollmentDate: "2025-06-28",
      previousSchool: "Gymnasium München",
      initialAssessment: "Pending",
      parentContact: "Maria Müller - maria.mueller@email.de",
      emergencyContact: "+49 89 123456789",
      specialNeeds: "None",
      mathLevel: "Advanced",
    },
    relatedEntities: {
      students: ["max-muller"],
      groups: ["8B"],
    },
  },
  {
    id: "geometrie-anfanger",
    type: "book",
    title: "Book Request Submitted",
    description: "Book request submitted for 'Geometrie für Anfänger'",
    timestamp: "2025-06-26T16:45:00Z",
    status: "pending",
    details: {
      bookTitle: "Geometrie für Anfänger",
      author: "Dr. Maria Schmidt",
      isbn: "978-3-12-345678-9",
      publisher: "Mathematik Verlag",
      requestedBy: "Teacher Anna",
      reason: "Needed for upcoming geometry unit in Grade 9",
      estimatedCost: "€29.99",
      approvalStatus: "Pending",
      expectedDelivery: "2025-07-05",
      quantity: 5,
      priority: "Medium",
      budgetCode: "MATH-2025-Q2",
    },
    relatedEntities: {
      books: ["geometrie-anfanger"],
    },
  },
  {
    id: "assignment-overdue",
    type: "assignment",
    title: "Assignment Overdue Alert",
    description: "3 students have overdue assignments in 'Quadratic Equations'",
    timestamp: "2025-06-29T09:00:00Z",
    status: "failed",
    details: {
      assignmentName: "Quadratic Equations",
      overdueStudents: ["Tom Fischer", "Sarah Klein", "Leon Hoffmann"],
      dueDate: "2025-06-27",
      daysOverdue: 2,
      notificationsSent: 3,
      parentContactRequired: true,
      extensionRequested: false,
      penaltyApplied: "10% per day",
      teacherNotes:
        "Students struggling with concept. Consider additional tutoring.",
    },
    relatedEntities: {
      assignments: ["quadratic-equations"],
      students: ["tom-fischer", "sarah-klein", "leon-hoffmann"],
    },
  },
  {
    id: "system-backup",
    type: "system",
    title: "System Backup Completed",
    description: "Daily system backup completed successfully",
    timestamp: "2025-06-29T02:00:00Z",
    status: "completed",
    details: {
      backupSize: "2.3 GB",
      duration: "12 minutes",
      filesBackedUp: 15847,
      location: "Cloud Storage - EU West",
      nextBackup: "2025-06-30T02:00:00Z",
      backupType: "Incremental",
      compressionRatio: "65%",
      verificationStatus: "Passed",
    },
    relatedEntities: {},
  },
  {
    id: "group-performance-update",
    type: "system",
    title: "Weekly Performance Report",
    description: "Weekly performance analytics generated for all groups",
    timestamp: "2025-06-28T18:00:00Z",
    status: "completed",
    details: {
      reportPeriod: "Week 26, 2025",
      groupsAnalyzed: 8,
      studentsAnalyzed: 156,
      assignmentsReviewed: 32,
      averagePerformance: 82,
      improvementTrends: ["Group 7A: +5%", "Group 8B: +3%"],
      concernAreas: ["Group 9C: -2%"],
    },
    relatedEntities: {
      groups: ["7A", "8B", "9C"],
    },
  },
];
